# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'Firebase/Core'
pod 'Firebase/Database'
target 'testNative1' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for testNative1

  target 'testNative1-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testNative1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end


  # Pods for testNative1-tvOS

